/** code generated by Kinyoshi */
package net.minecraft.src;

import java.util.Random;

public class BiomeGenStoneBasin extends BiomeGenBase
{
public BiomeGenStoneBasin(int par1)
{
	 super(par1);
	 this.spawnableCreatureList.clear();
	 this.spawnableWaterCreatureList.clear();
	 this.topBlock = (byte)Block.stone.blockID;
	 this.fillerBlock = (byte)Block.stone.blockID;
	 this.theBiomeDecorator.mushroomsPerChunk = 8;
     this.waterColorMultiplier = 14741066;
     this.theBiomeDecorator.treesPerChunk = 4;
     this.theBiomeDecorator.reedsPerChunk = 10;
     this.theBiomeDecorator.clayPerChunk = 14;
     this.theBiomeDecorator.waterlilyPerChunk = 10;
     this.theBiomeDecorator.sandPerChunk = -100;
     this.theBiomeDecorator.treesPerChunk = -100;
     this.theBiomeDecorator.flowersPerChunk = -100;
     this.theBiomeDecorator.grassPerChunk = -100;

	 this.spawnableMonsterList.add(new SpawnListEntry(EntityOcelot.class, 2, 1, 1));
     this.spawnableCreatureList.add(new SpawnListEntry(EntityChicken.class, 10, 4, 4));
	 this.minHeight = 0.0F;
	 this.maxHeight = 0.225F;
}

    public void decorate(World par1World, Random par2Random, int par3, int par4)
    {
        super.decorate(par1World, par2Random, par3, par4);

        for (int var6 = 0; var6 < 3 + par2Random.nextInt(3); ++var6)
        {
            int var7 = par3 + par2Random.nextInt(16);
            int var8 = par2Random.nextInt(28) + 7;
            int var9 = par4 + par2Random.nextInt(16);
            int var10 = par1World.getBlockId(var7, var8, var9);
            
            if (var10 == Block.stone.blockID)
            {
                par1World.setBlock(var7, var8, var9, Block.dirt.blockID);
            }
        }
        

        
        
        
    }


}