/** code generated by Kinyoshi */
package net.minecraft.src;

import java.util.Random;
import java.io.*;
import java.util.*;
import net.minecraft.client.Minecraft;

public class mod_StoneBasin extends BaseMod
{
	
    public mod_StoneBasin()
    {
       	readWriteProperties();	
    	
    	BiomeGenBase StoneBasin = (new BiomeGenStoneBasin(BiomeStoneBasinID)).setBiomeName("StoneBasin");	
        ModLoader.addBiome(StoneBasin);
    }
    
    	public void readWriteProperties() {
		Properties properties = new Properties();
		try
		{	
            File file = new File((new StringBuilder()).append(Minecraft.getMinecraftDir()).append("/mods/StoneBasin.config").toString());
            boolean flag = file.createNewFile();
            if(flag)
            {
                FileOutputStream fileoutputstream = new FileOutputStream(file);
                properties.setProperty("BiomeStoneBasinID", Integer.toString(101));
                properties.store(fileoutputstream, "Change the ID's to fix ID incompatibilities.");
                fileoutputstream.close();
            }
            properties.load(new FileInputStream((new StringBuilder()).append(Minecraft.getMinecraftDir()).append("/mods/StoneBasin.config").toString()));
            BiomeStoneBasinID = Integer.parseInt(properties.getProperty("BiomeStoneBasinID"));
        }
        catch(IOException ioexception)
        {
            ioexception.printStackTrace();
            BiomeStoneBasinID = 101;         
        }
	}

    public static int BiomeStoneBasinID;
    
    public String getVersion()
    {
        return "MineCraft1.5.2__mod_StoneBasin1.5.2r1";
    }
    

   
    public void load()
      	{
    	}
}
